GET http://localhost:4000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJqb2FvIiwiaWF0IjoxNzIyMzgxNTc3LCJleHAiOjE3MjIzODE2Mzd9.s9IRUdlKxZPaerq4I6Cj8X0dCbXfLYh_0-4MRLJiZC4

###

POST http://localhost:4000/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJqb2FvIiwiaWF0IjoxNzIyMzgxNTAyfQ.G155_koBUZIx2CpnejIqvARUbiotixNNkLnpUmjlV7g"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJqb2FvIiwiaWF0IjoxNzIyMzgxNTAyfQ.G155_koBUZIx2CpnejIqvARUbiotixNNkLnpUmjlV7g"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "joao",
    "password": "123"
}

###

POST http://localhost:4000/signup
Content-Type: application/json

{
    "username": "joao",
    "password": "123"
}