GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9hbyIsImlhdCI6MTcyMjM1MzAzOCwiZXhwIjoxNzIyMzUzMDk4fQ.FQhCujMHk3GFmXaCLT8WxqZ22mXHPATt48Yr2t3YsKw
###

POST http://localhost:4000/refreshToken
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoianAiLCJpYXQiOjE3MjIzNTI4NDJ9.uMM2XM74yBqMKPuk1MpSAszjzrg-Lqxy8PXNG2R6Spc"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidml0b3IiLCJpYXQiOjE3MjIzNTIyNzJ9.93T_tBy-2toeDeEmbuC8dRQ9Sgc6RRaJgb_uz0HOKOI"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "joao",
    "password": "123"
}

###

POST http://localhost:4000/signup
Content-Type: application/json

{
    "username": "joao",
    "password": "123"
}