GET http://localhost:3000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9hbyIsImlhdCI6MTcyMjM1MDQ0OSwiZXhwIjoxNzIyMzUwNTA5fQ.izVmvBBLEplv5hNV5FiOQdEfXvfqrbcXaTZcqjoaQgQ

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9hbyIsImlhdCI6MTcyMjM1MDQxMn0.mTqoIPm9fq5SabJS_21D3hhtTQGfS1jwsMhEaPAQbQA"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiam9hbyIsImlhdCI6MTcyMjMzODE1OX0.6HZBOklyHyayEW12-RlG1UgIb93THh1nYZpcZhD4sxc"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "joao",
    "password": "123456"
}

###

POST http://localhost:4000/signup
Content-Type: application/json

{
    "username": "joao",
    "password": "123456"
}